"""Internationalization support for Markdown assessment reports."""

from __future__ import annotations

import json
import os
from collections.abc import Mapping
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

from kubeoptix_core_ai.errors import ConfigurationError

SYSTEM_SETTINGS_BASE_URL = "http://localhost:8000"
SYSTEM_SETTINGS_PATH = "/system-settings"
SUPPORTED_LOCALES = ("pt-BR", "en-US", "es-ES", "it-IT")
_BABEL_LANGUAGES = {
    "pt-BR": "brazil",
    "en-US": "american",
    "es-ES": "spanish",
    "it-IT": "italian",
}

_TRANSLATIONS: dict[str, dict[str, str]] = {
    "pt-BR": {},
    "en-US": {
        "Relatório de Assessment": "Assessment Report",
        "Namespace analisado": "Analyzed namespace",
        "Fonte dos dados": "Data source",
        "Worknodes": "Worknodes",
        "Data de geração": "Generated at",
        "Gerado por": "Generated by",
        "Sumário executivo": "Executive summary",
        "Inventário do namespace / aplicações": "Namespace / application inventory",
        "Arquitetura reversa": "Reverse architecture",
        "Recursos de CPU e memória": "CPU and memory resources",
        "Observabilidade (métricas, logs, monitoramento)": "Observability (metrics, logs, monitoring)",
        "ConfigMaps e dados sensíveis (secrets, chaves, certificados)": "ConfigMaps and sensitive data (secrets, keys, certificates)",
        "Plano de ação": "Action plan",
        "Referências utilizadas": "References",
        "Arquivos processados (amostra)": "Processed files (sample)",
        "Workloads consolidados": "Consolidated workloads",
        "Detalhamento por workload": "Workload details",
        "Placement observado": "Observed placement",
        "Redistribuição sugerida do namespace": "Suggested namespace redistribution",
        "Comparativo request / limit / uso (snapshot)": "Request / limit / usage comparison (snapshot)",
        "Visualizações": "Visualizations",
        "Secrets referenciados": "Referenced Secrets",
        "Logs de pods (amostra)": "Pod logs (sample)",
        "Finding de arquitetura / redistribuição de namespace": "Architecture / namespace redistribution finding",
        "Findings de Events": "Event findings",
        "Findings de observabilidade e logs": "Observability and log findings",
        "Principais achados": "Key findings",
        "Fontes de dados": "Data sources",
        "Workloads analisados": "Analyzed workloads",
        "Worknodes considerados": "Worknodes considered",
        "Arquivos encontrados": "Files found",
        "Arquivos processados": "Files processed",
        "Arquivos ignorados": "Files ignored",
        "Erros de parsing": "Parsing errors",
        "Camada ML local": "Local ML layer",
        "ativada": "enabled",
        "desativada": "disabled",
        "Nenhum dado disponível.": "No data available.",
        "Nenhuma": "None",
        "indisponível": "unavailable",
        "Observação": "Note",
        "Métrica": "Metric",
        "Valor": "Value",
        "Workload": "Workload",
        "Quantidade": "Count",
        "Réplicas": "Replicas",
        "Serviço": "Service",
        "Serviço destino": "Target service",
        "Tipo": "Type",
        "Seletor": "Selector",
        "Evidência": "Evidence",
        "Análise": "Analysis",
        "Impacto potencial": "Potential impact",
        "Recomendação": "Recommendation",
        "Limitação": "Limitation",
        "Origem dos dados": "Data origin",
        "Confiança": "Confidence",
        "Severidade": "Severity",
        "Nenhuma recomendação específica gerada.": "No specific recommendation was generated.",
        "Nenhum risco classificado como HIGH ou CRITICAL.": "No risk classified as HIGH or CRITICAL.",
        "Nenhuma oportunidade de otimização identificada com os dados atuais.": "No optimization opportunity identified with the current data.",
        "Referência": "Reference",
        "Relevância": "Relevance",
        "Tema": "Topic",
        "Descrição": "Description",
        "Sigla": "Abbreviation",
        "Termos técnicos": "Technical terms",
        "Categorias de findings": "Finding categories",
        "Níveis de severidade": "Severity levels",
        "Níveis de confiança": "Confidence levels",
    },
    "es-ES": {
        "Relatório de Assessment": "Informe de evaluación",
        "Namespace analisado": "Namespace analizado",
        "Fonte dos dados": "Fuente de datos",
        "Data de geração": "Fecha de generación",
        "Gerado por": "Generado por",
        "Sumário executivo": "Resumen ejecutivo",
        "Inventário do namespace / aplicações": "Inventario del namespace / aplicaciones",
        "Arquitetura reversa": "Arquitectura inversa",
        "Recursos de CPU e memória": "Recursos de CPU y memoria",
        "Observabilidade (métricas, logs, monitoramento)": "Observabilidad (métricas, registros, monitorización)",
        "ConfigMaps e dados sensíveis (secrets, chaves, certificados)": "ConfigMaps y datos sensibles (secretos, claves, certificados)",
        "Plano de ação": "Plan de acción",
        "Referências utilizadas": "Referencias utilizadas",
        "Fontes de dados": "Fuentes de datos",
        "Workloads consolidados": "Workloads consolidados",
        "Detalhamento por workload": "Detalles por workload",
        "Placement observado": "Placement observado",
        "Redistribuição sugerida do namespace": "Redistribución sugerida del namespace",
        "Visualizações": "Visualizaciones",
        "Secrets referenciados": "Secrets referenciados",
        "Logs de pods (amostra)": "Registros de pods (muestra)",
        "Comparativo request / limit / uso (snapshot)": "Comparación request / limit / uso (instantánea)",
        "Principais achados": "Hallazgos principales",
        "Workloads analisados": "Workloads analizados",
        "Worknodes considerados": "Worknodes considerados",
        "Arquivos encontrados": "Archivos encontrados",
        "Arquivos processados": "Archivos procesados",
        "Arquivos ignorados": "Archivos ignorados",
        "Erros de parsing": "Errores de análisis",
        "Camada ML local": "Capa ML local",
        "ativada": "activada",
        "desativada": "desactivada",
        "Nenhum dado disponível.": "No hay datos disponibles.",
        "Nenhuma": "Ninguna",
        "indisponível": "no disponible",
        "Observação": "Observación",
        "Métrica": "Métrica",
        "Valor": "Valor",
        "Quantidade": "Cantidad",
        "Réplicas": "Réplicas",
        "Serviço destino": "Servicio destino",
        "Tipo": "Tipo",
        "Seletor": "Selector",
        "Evidência": "Evidencia",
        "Análise": "Análisis",
        "Impacto potencial": "Impacto potencial",
        "Recomendação": "Recomendación",
        "Limitação": "Limitación",
        "Origem dos dados": "Origen de los datos",
        "Confiança": "Confianza",
        "Severidade": "Severidad",
        "Referência": "Referencia",
        "Relevância": "Relevancia",
        "Tema": "Tema",
        "Descrição": "Descripción",
        "Termos técnicos": "Términos técnicos",
    },
    "it-IT": {
        "Relatório de Assessment": "Rapporto di valutazione",
        "Namespace analisado": "Namespace analizzato",
        "Fonte dos dados": "Origine dei dati",
        "Data de geração": "Data di generazione",
        "Gerado por": "Generato da",
        "Sumário executivo": "Riepilogo esecutivo",
        "Inventário do namespace / aplicações": "Inventario del namespace / applicazioni",
        "Arquitetura reversa": "Architettura inversa",
        "Recursos de CPU e memória": "Risorse CPU e memoria",
        "Observabilidade (métricas, logs, monitoramento)": "Osservabilità (metriche, log, monitoraggio)",
        "ConfigMaps e dados sensíveis (secrets, chaves, certificados)": "ConfigMaps e dati sensibili (segreti, chiavi, certificati)",
        "Plano de ação": "Piano d'azione",
        "Referências utilizadas": "Riferimenti utilizzati",
        "Fontes de dados": "Fonti dei dati",
        "Workloads consolidados": "Workload consolidati",
        "Detalhamento por workload": "Dettagli del workload",
        "Placement observado": "Placement osservato",
        "Redistribuição sugerida do namespace": "Ridistribuzione suggerita del namespace",
        "Visualizações": "Visualizzazioni",
        "Secrets referenciados": "Secret referenziati",
        "Logs de pods (amostra)": "Log dei pod (campione)",
        "Comparativo request / limit / uso (snapshot)": "Confronto request / limit / uso (istantanea)",
        "Principais achados": "Risultati principali",
        "Workloads analisados": "Workload analizzati",
        "Worknodes considerados": "Worknode considerati",
        "Arquivos encontrados": "File trovati",
        "Arquivos processados": "File elaborati",
        "Arquivos ignorados": "File ignorati",
        "Erros de parsing": "Errori di parsing",
        "Camada ML local": "Livello ML locale",
        "ativada": "attivata",
        "desativada": "disattivata",
        "Nenhum dado disponível.": "Nessun dato disponibile.",
        "Nenhuma": "Nessuna",
        "indisponível": "non disponibile",
        "Observação": "Nota",
        "Métrica": "Metrica",
        "Valor": "Valore",
        "Quantidade": "Quantità",
        "Réplicas": "Repliche",
        "Serviço destino": "Servizio di destinazione",
        "Tipo": "Tipo",
        "Seletor": "Selettore",
        "Evidência": "Evidenza",
        "Análise": "Analisi",
        "Impacto potencial": "Impatto potenziale",
        "Recomendação": "Raccomandazione",
        "Limitação": "Limitazione",
        "Origem dos dados": "Origine dei dati",
        "Confiança": "Affidabilità",
        "Severidade": "Gravità",
        "Referência": "Riferimento",
        "Relevância": "Rilevanza",
        "Tema": "Argomento",
        "Descrição": "Descrizione",
        "Termos técnicos": "Termini tecnici",
    },
}


def validate_locale(language: object) -> str:
    """Validate an exact, case-sensitive supported BCP 47 locale."""
    if not isinstance(language, str) or language not in SUPPORTED_LOCALES:
        received = repr(language)
        raise ConfigurationError(
            f"Locale não suportado recebido de /system-settings: {received}. "
            "Informe exatamente um destes locales: "
            + ", ".join(SUPPORTED_LOCALES)
        )
    return language


def _system_settings_endpoint(url: str | None = None) -> str:
    base_url = (
        url
        or os.getenv("SYSTEM_SETTINGS_URL", "").strip()
        or os.getenv("KUBEOPTIX_SYSTEM_SETTINGS_URL", "").strip()
        or SYSTEM_SETTINGS_BASE_URL
    ).rstrip("/")
    if base_url.endswith(SYSTEM_SETTINGS_PATH):
        return base_url
    return f"{base_url}{SYSTEM_SETTINGS_PATH}"


def resolve_system_locale(*, url: str | None = None, timeout: float = 5.0) -> str:
    """Read and validate the report locale from the system-settings service."""
    endpoint = _system_settings_endpoint(url)
    request = Request(endpoint, headers={"Accept": "application/json"})
    try:
        with urlopen(request, timeout=timeout) as response:
            payload = json.load(response)
    except HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace").strip()
        detail = f": {body}" if body else ""
        raise ConfigurationError(
            f"Falha ao consultar {endpoint} (HTTP {exc.code}){detail}"
        ) from exc
    except URLError as exc:
        raise ConfigurationError(
            f"Não foi possível acessar {endpoint}: {exc.reason}"
        ) from exc
    except (OSError, TimeoutError, json.JSONDecodeError) as exc:
        raise ConfigurationError(
            f"Não foi possível consultar {endpoint}: {exc}"
        ) from exc
    if not isinstance(payload, Mapping):
        raise ConfigurationError("Resposta de /system-settings inválida.")
    return validate_locale(payload.get("language"))


def babel_language(locale: str) -> str:
    return _BABEL_LANGUAGES[validate_locale(locale)]


def translate_report(content: str, locale: str) -> str:
    """Translate user-facing report fragments while preserving technical values."""
    locale = validate_locale(locale)
    translations = _TRANSLATIONS[locale]
    for source, target in sorted(translations.items(), key=lambda item: len(item[0]), reverse=True):
        content = content.replace(source, target)
    return content
