apiVersion: v1
kind: Service
metadata:
  name: kubeoptix-core-ai-api
  labels:
    app.kubernetes.io/name: kubeoptix-core-ai-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kubeoptix-core-ai
spec:
  selector:
    app.kubernetes.io/name: kubeoptix-core-ai-api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  type: ClusterIP
