{{- if and .Values.enabled .Values.rbac.createClusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s-%s" (include "kubeoptix-core-ai.serviceAccountName" .) (include "kubeoptix-core-ai.namespace" .) .Values.rbac.clusterRoleName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "kubeoptix-core-ai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ required "rbac.clusterRoleName é obrigatório quando rbac.createClusterRoleBinding=true" .Values.rbac.clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeoptix-core-ai.serviceAccountName" . }}
    namespace: {{ include "kubeoptix-core-ai.namespace" . }}
{{- end }}
