{{- if and .Values.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeoptix-core-ai.serviceAccountName" . }}
  namespace: {{ include "kubeoptix-core-ai.namespace" . }}
  labels:
    {{- include "kubeoptix-core-ai.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
